
SELECT 
		ROW_NUMBER() OVER (ORDER BY [Nº de Licencia], [Posición Arancelaria], Año, Mes ) AS [Id],
        0 as [Consecutivo],
		[Día],
		[Mes],
		[Año],
		ISNULL([Tipo de Documento], '') AS [Tipo de Documento],
		ISNULL([Nº de Licencia], -1) AS [Nº de Licencia],
		ISNULL([Número de Preimpreso], 0) AS [Número de Preimpreso],
		ISNULL([Número de Aceptación], 0) AS [numero aceptación],
		ISNULL([Número de Declaracion de Importación], '') AS [Número de Declaracion de Importación],
		ISNULL([Número de Declaracion Anterior], '') AS [Número de Declaracion Anterior],
		ISNULL([Fecha Declaración Anterior], 0) AS [Fecha Declaración Anterior],
		ISNULL([Banco], '') AS [Banco],
		ISNULL([Tipo de Declaración], '') AS [Tipo de Declaración],
		ISNULL([Oficina de Aduana], '') AS [Oficina de Aduana],
		ISNULL([Régimen], '') AS [Régimen],
		ISNULL([NIT agente aduanero], 0) AS [NIT agente aduanero],
		ISNULL([Agente Aduanero], '') AS [Agente Aduanero],
		ISNULL([NIT del Importador], 0) AS [NIT del Importador],
		ISNULL([Razón Social del Importador], '') AS [Razón Social del Importador],
		ISNULL([Dpto. del Importador], '') AS [Dpto# del Importador],
		ISNULL([Nombre del Representante Jurídico], '') AS [Nombre del Representante Jurídico],
		ISNULL([Documento del Representante Jurídico], 0) AS [Documento del Representante Jurídico],
		ISNULL([Dirección Importador], '') AS [Dirección Importador],
		ISNULL([Tel. del Importador], 0) AS [Tel# del Importador],
		ISNULL([Actividad Económica del Importador], 0) AS [Actividad Económica del Importador],
		ISNULL([Descripción de la Mercancía 2], '') AS [Descripción de la Mercancía 2],
		ISNULL([Posición Arancelaria], 0) AS [Posición Arancelaria],
		ISNULL([Designación de la Mercancía], '') AS [Designación de la Mercancía],
		ISNULL([Descripción de la Mercancía], '') AS [Descripción de la Mercancía],
		ISNULL([Cantidad], 0) AS [Cantidad],
		ISNULL([Unidad Comercial], '') AS [Unidad Comercial],
		ISNULL([Número de Bultos], 0) AS [Número de Bultos],
		ISNULL([Embalaje], '') AS [Embalaje],
		ISNULL([Peso Neto Kgs.], 0) AS [Peso Neto Kgs#],
		ISNULL([Peso Bruto Kgs.], 0) AS [Peso Bruto Kgs#],
		ISNULL([Acuerdo], '') AS [Acuerdo],
		ISNULL([Depósito], '') AS [Depósito],
		ISNULL([País de Origen], '') AS [País de Origen],
		ISNULL([País Procedencia], '') AS [País Procedencia],
		ISNULL([País de Compra], '') AS [País de Compra],
		ISNULL([Lugar de Ingreso], '') AS [Lugar de Ingreso],
		ISNULL([Dpto. de Ingreso], '') AS [Dpto# de Ingreso],
		ISNULL([No. De la factura], '') AS [No# De la factura],
		ISNULL([Fecha de la factura], 0) AS [Fecha de la factura],
		ISNULL([Proveedor], '') AS [Proveedor],
		ISNULL([Ciudad/País del Proveedor], '') AS [Ciudad/País del Proveedor],
		ISNULL([Dirección del Proveedor], '') AS [Dirección del Proveedor],
		ISNULL([Contacto del Proveedor], '') AS [Contacto del Proveedor],
		ISNULL([Nº de Manifiesto], 0) AS [Nº de Manifiesto],
		ISNULL([Fecha del Manifiesto], 0) AS [Fecha del Manifiesto],
		ISNULL([Documento de Transporte], '') AS [Documento de Transporte],
		ISNULL([Transporte], '') AS [Transporte],
		ISNULL([Transportador], '') AS [Transportador],
		ISNULL([Tasa de Cambio COP$], 0) AS [Tasa de Cambio COP$],
		ISNULL([Forma de Pago], '') AS [Forma de Pago],
		ISNULL([Porcentaje Arancel], 0) AS [Porcentaje Arancel],
		ISNULL([Porcentaje IVA], 0) AS [Porcentaje IVA],
		ISNULL([Vlr Total Arancel], 0) AS [Vlr Total Arancel],
		ISNULL([Vlr Total IVA], 0) AS [Vlr Total IVA],
		ISNULL([Valor Otros], 0) AS [Valor Otros],
		ISNULL([Valor Sanciones], 0) AS [Valor Sanciones],
		ISNULL([Sanciones Pagadas], 0) AS [Sanciones Pagadas],
		ISNULL([Valor a Pagar], 0) AS [Valor a Pagar],
		ISNULL([Otros pagados], 0) AS [Otros pagados],
		ISNULL([Arancel Pagado COP], 0) AS [Arancel Pagado COP],
		ISNULL([IVA Pagado COP], 0) AS [IVA Pagado COP],
		ISNULL([Valor Fletes y Seguros USD], 0) AS [Valor Fletes y Seguros USD],
		ISNULL([Flete USD], 0) AS [Flete USD],
		ISNULL([Seguro USD], 0) AS [Seguro USD],
		ISNULL([Otros Gastos USD], 0) AS [Otros Gastos USD],
		ISNULL([Porcentaje Salvaguardia], 0) AS [Porcentaje Salvaguardia],
		ISNULL([Vlr. Total Salvaguardia COP], 0) AS [Vlr# Total Salvaguardia COP],
		ISNULL([Porcentaje de Derechos Compensatorios], 0) AS [Porcentaje de Derechos Compensatorios],
		ISNULL([Base Derechos Compensatorios USD], 0) AS [Base Derechos Compensatorios USD],
		ISNULL([Vlr Total Derechos Compensatorios COP], 0) AS [Vlr Total Derechos Compensatorios COP],
		ISNULL([Porcentaje Dumping], 0) AS [Porcentaje Dumping],
		ISNULL([Base Dumping USD], 0) AS [Base Dumping USD],
		ISNULL([Vlr. Total Dumping COP], 0) AS [Vlr# Total Dumping COP],
		ISNULL([Precio FOB USD Unitario], 0) AS [Precio FOB USD Unitario],
		ISNULL([Precio FOB USD Kg Neto], 0) AS [Precio FOB USD Kg Neto],
		ISNULL([valor fob US$], 0) AS [valor fob US$],
		ISNULL([valor FOB COP$], 0) AS [valor FOB COP$],
		ISNULL([Precio CIF USD Unitario], 0) AS [Precio CIF USD Unitario],
		ISNULL([Precio CIF USD Kg Neto], 0) AS [Precio CIF USD Kg Neto],
		ISNULL([valor cif US $], 0) AS [valor cif US $],
		ISNULL([valor CIF COP$], 0) AS [valor CIF COP$],
		ISNULL([Vlr. Ajustes], 0) AS [Vlr# Ajustes],
		NULL AS ConsecutivoItem,
		MesNumero
FROM 
(
	{0}
	) AS Data


